import type { MotionClip } from "./types";

/** 17 моушн-роликов. mp4 и постер-кадр лежат в `public/video`. */
export const MOTION: MotionClip[] = [
  {
    kind: "motion",
    slug: "mo-kaspi-pidjak",
    video: "video/kaspi-pidjak.mp4",
    poster: "video/kaspi-pidjak.jpg",
    cat: "biz",
    title: "Kaspi · Asyl Pidjak",
    dur: "0:15",
    desc: "Динамичный промо-ролик к акции с быстрым монтажом, кинетической типографикой и брендовыми акцентами Kaspi.",
    tools: ["After Effects", "Photoshop"],
    features: ["Кинетическая типографика", "Ограниченная по времени акция", "Брендовые цвета и логотип"],
  },
  {
    kind: "motion",
    slug: "mo-evrookna",
    video: "video/evrookna.mp4",
    poster: "video/evrookna.jpg",
    cat: "biz",
    title: "Евро Окна · Розыгрыш",
    dur: "0:25",
    desc: "Анимационный ролик розыгрыша с призовым фондом: 3D-подарок, летящие реакции и крупный призовой оффер.",
    tools: ["After Effects", "Photoshop"],
    features: ["3D-элементы и партиклы", "Акцент на призовом фонде", "Плавные переходы сцен"],
  },
  {
    kind: "motion",
    slug: "mo-m2-shoes",
    video: "video/m2-shoes.mp4",
    poster: "video/m2-shoes.jpg",
    cat: "biz",
    title: "M2 · Обувь к лету",
    dur: "0:15",
    desc: "Ритейл-креатив к сезонной коллекции обуви с эффектным появлением товара и чётким призывом к покупке.",
    tools: ["After Effects", "Photoshop"],
    features: ["Сезонный оффер", "Акцент на продукте", "Крупный CTA"],
  },
  {
    kind: "motion",
    slug: "mo-wedding-invite",
    video: "video/wedding-invite.mp4",
    poster: "video/wedding-invite.jpg",
    cat: "event",
    title: "Свадебное приглашение",
    dur: "0:30",
    desc: "Анимированное приглашение в национальном стиле: цветочные рамки, каллиграфия и мягкое проявление деталей.",
    tools: ["After Effects", "Photoshop"],
    features: ["Национальная эстетика", "Каллиграфия и орнаменты", "Мягкая анимация появления"],
  },
  {
    kind: "motion",
    slug: "mo-ekopol",
    video: "video/ekopol.mp4",
    poster: "video/ekopol.jpg",
    cat: "biz",
    title: "Экопол · Покрытия",
    dur: "0:12",
    desc: "Продуктовый ролик напольных покрытий с чистой сценой интерьера и понятным ограниченным по срокам оффером.",
    tools: ["After Effects", "Photoshop"],
    features: ["Интерьерная сцена", "Демонстрация фактур", "Срочный оффер"],
  },
  {
    kind: "motion",
    slug: "mo-valentine",
    video: "video/valentine.mp4",
    poster: "video/valentine.jpg",
    cat: "event",
    title: "День влюблённых",
    dur: "0:15",
    desc: "Праздничный креатив ко Дню влюблённых: тёплая эмоция, сердца-партиклы и акцентная подарочная механика.",
    tools: ["After Effects", "Photoshop"],
    features: ["Праздничная тематика", "Эмоциональный посыл", "Партиклы и акценты"],
  },
  {
    kind: "motion",
    slug: "mo-doremi",
    video: "video/doremi.mp4",
    poster: "video/doremi.jpg",
    cat: "biz",
    title: "Do Re Mi · Караоке",
    dur: "0:30",
    desc: "Атмосферный ролик караоке-клуба с неоновой подачей, ритмичным монтажом и клубным настроением.",
    tools: ["After Effects", "Premiere Pro"],
    features: ["Неоновая эстетика", "Ритмичный монтаж", "Клубное настроение"],
  },
  {
    kind: "motion",
    slug: "mo-astana-kitchen",
    video: "video/astana-kitchen.mp4",
    poster: "video/astana-kitchen.jpg",
    cat: "biz",
    title: "Astana Kitchens · Кухни",
    dur: "0:15",
    desc: "Имиджевый ролик кухонь на заказ: аккуратные проходы по интерьеру и акцент на индивидуальном проекте.",
    tools: ["After Effects", "Photoshop"],
    features: ["Интерьерная съёмка", "Акцент на индивидуальности", "Спокойная премиальная подача"],
  },
  {
    kind: "motion",
    slug: "mo-dmu-grant",
    video: "video/dmu-grant.mp4",
    poster: "video/dmu-grant.jpg",
    cat: "edu",
    title: "De Montfort · Грант 50%",
    dur: "0:15",
    desc: "Образовательный креатив с грант-оффером: живой герой, крупный процент скидки и понятная выгода для абитуриента.",
    tools: ["After Effects", "Photoshop"],
    features: ["Крупный грант-оффер", "Фокус на герое", "Чёткая выгода"],
  },
  {
    kind: "motion",
    slug: "mo-adalada",
    video: "video/adalada.mp4",
    poster: "video/adalada.jpg",
    cat: "biz",
    title: "Adal Ada · Клининг",
    dur: "0:15",
    desc: "Сервисный ролик клининга с чистой светлой графикой, иконографикой и акцентом на экономии времени.",
    tools: ["After Effects", "Photoshop"],
    features: ["Светлая чистая графика", "Иконографика услуги", "Акцент на времени"],
  },
  {
    kind: "motion",
    slug: "mo-sapfirdent",
    video: "video/sapfirdent.mp4",
    poster: "video/sapfirdent.jpg",
    cat: "biz",
    title: "Sapfir Dent · Стоматология",
    dur: "0:15",
    desc: "Промо стоматологии с механикой рассрочки Kaspi RED, дружелюбным героем и понятным призывом записаться.",
    tools: ["After Effects", "Photoshop"],
    features: ["Механика рассрочки", "Дружелюбный тон", "Понятный CTA"],
  },
  {
    kind: "motion",
    slug: "mo-sneakers",
    video: "video/sneakers.mp4",
    poster: "video/sneakers.jpg",
    cat: "biz",
    title: "Sneakers · Промо",
    dur: "0:12",
    desc: "Энергичный промо-ролик кроссовок с резким sporty-монтажом, диагональной динамикой и ценовым акцентом.",
    tools: ["After Effects", "Photoshop"],
    features: ["Спортивная динамика", "Диагональная композиция", "Ценовой акцент"],
  },
  {
    kind: "motion",
    slug: "mo-tooman",
    video: "video/tooman.mp4",
    poster: "video/tooman.jpg",
    cat: "biz",
    title: "Tooman · Кальян-бар",
    dur: "0:15",
    desc: "Атмосферный вертикальный ролик заведения: дымка, тёплый свет и приглашение на вечер.",
    tools: ["After Effects", "Premiere Pro"],
    features: ["Вертикальный формат", "Атмосферный свет", "Приглашающий посыл"],
  },
  {
    kind: "motion",
    slug: "mo-gorod-grehov",
    video: "video/gorod-grehov.mp4",
    poster: "video/gorod-grehov.jpg",
    cat: "event",
    title: "Город Грехов · Акция",
    dur: "0:12",
    desc: "Праздничный ивент-креатив для караоке-клуба: акция именинникам, блеск, конфетти и щедрая скидка.",
    tools: ["After Effects", "Photoshop"],
    features: ["Ивент-механика", "Праздничные партиклы", "Крупная скидка"],
  },
  {
    kind: "motion",
    slug: "mo-rostex",
    video: "video/rostex.mp4",
    poster: "video/rostex.jpg",
    cat: "biz",
    title: "Ros-Tex · Домашний текстиль",
    dur: "0:15",
    desc: "Имиджевый ролик текстильного бренда с национальным акцентом, мягкой подачей и эмоцией преемственности.",
    tools: ["After Effects", "Photoshop"],
    features: ["Национальный акцент", "Мягкая эмоция", "Премиальная фактура"],
  },
  {
    kind: "motion",
    slug: "mo-novy-dom",
    video: "video/novy-dom.mp4",
    poster: "video/novy-dom.jpg",
    cat: "biz",
    title: "Новый дом · Мебель",
    dur: "0:20",
    desc: "Продуктовый ролик мебели для ванной с чистыми проходами по интерьеру и вовлекающим вопросом-оффером.",
    tools: ["After Effects", "Photoshop"],
    features: ["Интерьерные проходы", "Вопрос-оффер", "Аккуратная типографика"],
  },
  {
    kind: "motion",
    slug: "mo-it-challenge",
    video: "video/it-challenge.mp4",
    poster: "video/it-challenge.jpg",
    cat: "edu",
    title: "IT-Challenge 2026",
    dur: "0:30",
    desc: "Технологичный ивент-креатив студенческого IT-турнира: код-эстетика, глитч-акценты и стипендиальный оффер.",
    tools: ["After Effects", "Photoshop"],
    features: ["Код-эстетика и глитч", "Крупный оффер стипендии", "Технологичная подача"],
  },
];
