import type { Work } from "./types";

/** 64 статичных креатива. Изображения лежат в `public/img`. */
export const WORKS: Work[] = [
  {
    kind: "work",
    slug: "dmu-ent-grant",
    src: "img/dmu-ent-grant.jpg",
    cat: "edu",
    title: "Не получил гос. грант?",
    tools: ["Photoshop", "Figma"],
    desc: "Оффер-креатив для абитуриентов, не прошедших на государственный грант: университет предлагает частичный грант до 50% на весь период обучения.",
    features: ["Жест героя ведёт взгляд к офферу", "Наградная лента TOP 117", "Дефицит: «количество мест ограничено»"],
  },
  {
    kind: "work",
    slug: "dmu-mba-masterclass",
    src: "img/dmu-mba-masterclass.jpg",
    cat: "event",
    title: "Global MBA — мастер-класс",
    tools: ["Photoshop", "Figma"],
    desc: "Анонс мастер-класса «Persuasive Skills for Business Leaders» для руководителей и предпринимателей. Премиальная фиолетовая гамма и портрет спикера.",
    features: ["Фирменный вензель-тигр в фоне", "Золотой заголовок на глубоком фиолетовом", "Блок спикера с регалиями"],
  },
  {
    kind: "work",
    slug: "dmu-openday-watermelon",
    src: "img/dmu-openday-watermelon.jpg",
    cat: "event",
    title: "Open Day: Taste Your Future",
    tools: ["Photoshop", "Figma"],
    desc: "Летний Open Day с арбузной механикой и розыгрышем бесплатного IELTS. Живой коллаж из фото студентов, фруктов и тропических листьев.",
    features: ["Фото-коллаж с вырезкой", "Сочная летняя палитра", "Программа события как список"],
  },
  {
    kind: "work",
    slug: "dmu-openday-astana-tokyo",
    src: "img/dmu-openday-astana-tokyo.jpg",
    cat: "event",
    title: "День открытых дверей — Астана",
    tools: ["Photoshop", "Figma"],
    desc: "Городской Open Day в Астане: строгая бордовая гамма, портрет выпускницы в мантии и полный адрес площадки.",
    features: ["Жёлтый акцент на городе", "Крупный трёхстрочный заголовок", "Адрес и CTA в одном блоке"],
  },
  {
    kind: "work",
    slug: "cell-ielts-comprehensive",
    src: "img/cell-ielts-comprehensive.jpg",
    cat: "edu",
    title: "IELTS Comprehensive — новый набор",
    tools: ["Photoshop", "Figma"],
    desc: "Набор на комплексный курс IELTS от центра CELL. Все четыре модуля вынесены в отдельный блок с иконками, цель 7+ подана как визуальный якорь.",
    features: ["Иконки четырёх модулей", "Реквизит «IELTS 7+» в кадре", "Тёмно-синий фон с коралловыми акцентами"],
  },
  {
    kind: "work",
    slug: "cell-general-dark",
    src: "img/cell-general-dark.jpg",
    cat: "edu",
    title: "General English — набор (dark)",
    tools: ["Photoshop", "Figma"],
    desc: "Тёмная версия креатива для набора на General English: уровни курса, три выгоды и мотивирующий герой с британским флагом.",
    features: ["Уровни A2 / B2 как чек-лист", "Выделение выгод цветом", "Дефицит: «места ограничены»"],
  },
  {
    kind: "work",
    slug: "dmu-admissions-sept",
    src: "img/dmu-admissions-sept.jpg",
    cat: "edu",
    title: "Admissions are open until 15 September",
    tools: ["Photoshop", "Figma"],
    desc: "Англоязычный имиджевый креатив о наборе: премиальная монохромная сцена, антиква в заголовке и три ключевых преимущества с иконками.",
    features: ["Контраст антиквы и гротеска", "Монохромная премиальная сцена", "Дедлайн как главный аргумент"],
  },
  {
    kind: "work",
    slug: "dmu-openday-astana-feb",
    src: "img/dmu-openday-astana-feb.jpg",
    cat: "event",
    title: "Open Day в Астане — февраль",
    tools: ["Photoshop", "Figma"],
    desc: "Зимний Open Day в Астане: двойной портрет абитуриентов, крупный лок-ап названия университета и рукописный акцент «в Астане».",
    features: ["Каллиграфический акцент", "Двойной портрет в дуотоне", "Дата, время и адрес в капсулах"],
  },
  {
    kind: "work",
    slug: "cell-general-white",
    src: "img/cell-general-white.jpg",
    cat: "edu",
    title: "General English — набор (light)",
    tools: ["Photoshop", "Figma"],
    desc: "Светлая версия того же оффера: чистый белый фон, синий заголовок и три выгоды курса с галочками — максимальная читаемость в ленте.",
    features: ["Светлая чистая вёрстка", "Выгоды с чек-иконками", "CTA-плашка с WhatsApp"],
  },
  {
    kind: "work",
    slug: "dmu-british-chess",
    src: "img/dmu-british-chess.jpg",
    cat: "ai",
    title: "Стань частью британского университета",
    tools: ["AI-генерация", "Photoshop", "Figma"],
    desc: "Имиджевый креатив с AI-сценой: шахматная пешка отражается в зеркале королевой — метафора роста через британское образование.",
    features: ["AI-генерация ключевой сцены", "Метафора «пешка → королева»", "Три преимущества в тёмной карточке"],
  },
  {
    kind: "work",
    slug: "dmu-global-education-openday",
    src: "img/dmu-global-education-openday.jpg",
    cat: "event",
    title: "Global Education Open Day",
    tools: ["Photoshop", "Figma"],
    desc: "Анонс Open Day с двумя сессиями: светлая контрастная вёрстка, диагональный бордовый блок и стипендиальная механика как дополнительный стимул.",
    features: ["Съёмка героя сверху", "Диагональное деление композиции", "Время, адрес и бонус в отдельных блоках"],
  },
  {
    kind: "work",
    slug: "dmu-infosession-almaty",
    src: "img/dmu-infosession-almaty.jpg",
    cat: "event",
    title: "Инфосессия в DMU Kazakhstan",
    tools: ["Photoshop", "Figma"],
    desc: "Креатив инфосессии с панорамой Алматы: героиня с британским флагом на фоне города и гор, программа встречи подана как пронумерованный таймлайн.",
    features: ["Коллаж: город, горы, герой", "Таймлайн 01–02–03", "Курсивный лок-ап названия"],
  },
  {
    kind: "work",
    slug: "dmu-mba-admissions",
    src: "img/dmu-mba-admissions.jpg",
    cat: "edu",
    title: "Приём документов на Global MBA",
    tools: ["Photoshop", "Figma"],
    desc: "Оффер-креатив о приёме на Global MBA: требования по IELTS, четыре выгоды программы и рейтинговый пруф внизу макета.",
    features: ["Требование к IELTS как фильтр", "Четыре выгоды чек-листом", "Синий CTA на бордовом фоне"],
  },
  {
    kind: "work",
    slug: "mba-global",
    src: "img/mba-global.jpg",
    cat: "edu",
    title: "Global MBA — онлайн-вебинар",
    tools: ["Photoshop", "Figma"],
    desc: "Премиальный креатив для анонса вебинара по программе Global MBA. Тёмная кинематографичная подача, дуотон-портрет спикера и чёткая иерархия дат.",
    features: ["Дуотон-обработка портрета", "Кинематографичный градиент", "Акцент на дате и спикере"],
  },
  {
    kind: "work",
    slug: "mba-webinar",
    src: "img/mba-webinar.jpg",
    cat: "edu",
    title: "MBA: Finance for Non-Financial Managers",
    tools: ["Photoshop", "Illustrator"],
    desc: "Анонс финансового вебинара. Сочный красный, крупная контрастная типографика и фирменный блок с программой сессии.",
    features: ["Крупный type-lockup", "Контраст красный / жёлтый", "Список тем как оффер"],
  },
  {
    kind: "work",
    slug: "grant-50",
    src: "img/grant-50.jpg",
    cat: "edu",
    title: "Грант 50% на обучение",
    tools: ["Photoshop", "Figma"],
    desc: "Оффер-креатив про грант. Чистая красно-белая система, карточки-преимущества и явный CTA «Подать заявку».",
    features: ["Карточная инфографика", "Фирменный красный", "Сильный CTA"],
  },
  {
    kind: "work",
    slug: "dmuk-postupi",
    src: "img/dmuk-postupi.jpg",
    cat: "edu",
    title: "Поступи в DMU Kazakhstan",
    tools: ["Photoshop", "Figma"],
    desc: "Имиджевый креатив о поступлении с акцентом на британский диплом и грант до 50%.",
    features: ["Светлая лёгкая подача", "Бейдж «британский диплом»", "Плашка-оффер снизу"],
  },
  {
    kind: "work",
    slug: "camp-leaders",
    src: "img/camp-leaders.jpg",
    cat: "edu",
    title: "Лагерь для будущих лидеров",
    tools: ["Photoshop", "Figma"],
    desc: "Креатив для бизнес-интенсива. Свежий светло-голубой фон, чек-листы и аккуратный CTA.",
    features: ["Чек-лист буллеты", "Чистая сетка", "Деловой портрет"],
  },
  {
    kind: "work",
    slug: "english-trial",
    src: "img/english-trial.jpg",
    cat: "edu",
    title: "Пробный урок по английскому",
    tools: ["Photoshop", "Figma"],
    desc: "Лид-креатив на пробный урок. Дуотон-градиент, флаг и понятный оффер по форматам обучения.",
    features: ["Градиентный заголовок", "Бейджи форматов", "Тематическая графика"],
  },
  {
    kind: "work",
    slug: "ielts-prep",
    src: "img/ielts-prep.jpg",
    cat: "edu",
    title: "Подготовься к IELTS · CELL",
    tools: ["Photoshop", "Figma"],
    desc: "Креатив языкового центра. Светлая воздушная подача, иконки-преимущества и CTA Sign Up.",
    features: ["Иконочные буллеты", "Лёгкий фон", "Динамичный портрет"],
  },
  {
    kind: "work",
    slug: "it-challenge",
    src: "img/it-challenge.jpg",
    cat: "edu",
    title: "IT-Challenge 2026",
    tools: ["Photoshop", "Illustrator"],
    desc: "Конкурс-стипендия для будущих айтишников. Тёмный технологичный фон с кодом и медали призовых мест.",
    features: ["Код-фон", "Медали-призы", "Технологичная подача"],
  },
  {
    kind: "work",
    slug: "ielts-free",
    src: "img/ielts-free.jpg",
    cat: "edu",
    title: "Сдай IELTS бесплатно",
    tools: ["Photoshop", "Illustrator"],
    desc: "Хлёсткий перформанс-креатив. Гиперкрупный заголовок, тёплый красно-оранжевый градиент и оффер «за счёт преподавателя».",
    features: ["Гиперкрупный type", "Тёплый градиент", "Сильный хук"],
  },
  {
    kind: "work",
    slug: "ielts-seminar",
    src: "img/ielts-seminar.jpg",
    cat: "edu",
    title: "Бесплатный IELTS Seminar",
    tools: ["Photoshop", "Figma"],
    desc: "Анонс семинара совместно с American Space. Сдержанная светлая подача и читаемый блок деталей.",
    features: ["Co-brand логотипы", "Чистый layout", "Блок места и времени"],
  },
  {
    kind: "work",
    slug: "cell-open-day",
    src: "img/cell-open-day.jpg",
    cat: "edu",
    title: "CELL Open Day",
    tools: ["Photoshop", "Figma"],
    desc: "День открытых дверей языкового центра. Светлый фон с Биг-Беном, программа и розыгрыш мест.",
    features: ["Тематический фон Лондон", "Оффер-розыгрыш", "Понятная программа"],
  },
  {
    kind: "work",
    slug: "business-competition",
    src: "img/business-competition.jpg",
    cat: "event",
    title: "Business Competition",
    tools: ["Photoshop", "Figma"],
    desc: "Конкурс грантов для абитуриентов. Групповой портрет студентов, тёмно-синяя премиальная подача и градации призов.",
    features: ["Групповой портрет", "Скруглённый контейнер", "3 уровня грантов"],
  },
  {
    kind: "work",
    slug: "aqtau-event",
    src: "img/aqtau-event.jpg",
    cat: "event",
    title: "DMU в Aqtau · Open Day",
    tools: ["Photoshop", "Figma"],
    desc: "Ивент-креатив с кинематографичной ночной панорамой Актау. Глубокий синий, чёткий тайминг и блок «что тебя ждёт».",
    features: ["Кинематографичный фон", "Ночная панорама города", "Чёткая навигация по блокам"],
  },
  {
    kind: "work",
    slug: "open-day-shymkent",
    src: "img/open-day-shymkent.jpg",
    cat: "event",
    title: "Open Day в Шымкенте",
    tools: ["Photoshop", "Figma"],
    desc: "Анонс дня открытых дверей. Драматичный красно-чёрный градиент, рукописный акцент и явный CTA.",
    features: ["Рукописный акцент", "Красный градиент", "Двойной портрет"],
  },
  {
    kind: "work",
    slug: "nauryz-open-day",
    src: "img/nauryz-open-day.jpg",
    cat: "event",
    title: "Наурыз Open Day",
    tools: ["Photoshop", "Figma"],
    desc: "Праздничный весенний креатив. Нежно-розовая палитра, тюльпаны и казахский орнамент.",
    features: ["Сезонная палитра", "Орнамент-паттерн", "Тёплое настроение"],
  },
  {
    kind: "work",
    slug: "open-day-aktobe",
    src: "img/open-day-aktobe.jpg",
    cat: "event",
    title: "День открытых дверей · Актобе",
    tools: ["Photoshop", "Figma"],
    desc: "Региональный ивент-креатив. Светлая подача, рукописный топоним и блок деталей события.",
    features: ["Рукописный топоним", "Чистый layout", "Деталь места и времени"],
  },
  {
    kind: "work",
    slug: "foundation-collage",
    src: "img/foundation-collage.jpg",
    cat: "ai",
    title: "Foundation · Мост в мировое образование",
    tools: ["Photoshop", "Midjourney"],
    desc: "Концептуальная фотоманипуляция: чемодан-портал с мировыми достопримечательностями, самолёт и поезд в облаках. Сложный коллаж и ретушь.",
    features: ["Сложный фотоколлаж", "AI-генерация элементов", "Сюрреалистичная композиция"],
  },
  {
    kind: "work",
    slug: "ec-council",
    src: "img/ec-council.jpg",
    cat: "ai",
    title: "EC-Council Academia Partner",
    tools: ["Photoshop", "Midjourney"],
    desc: "Имиджевый креатив о партнёрстве. Неоновое 3D-рукопожатие из частиц на фоне крупного брендового леттеринга.",
    features: ["3D-частицы", "Неоновый градиент", "Крупный леттеринг-фон"],
  },
  {
    kind: "work",
    slug: "kamiwatch",
    src: "img/kamiwatch.jpg",
    cat: "biz",
    title: "KamiWatch · Рассрочка",
    tools: ["Photoshop"],
    desc: "Премиальный продуктовый креатив для часового бренда. Тёмный фон, золотые акценты и драматичный свет на продукте.",
    features: ["Премиальный свет", "Золотые акценты", "Фокус на продукте"],
  },
  {
    kind: "work",
    slug: "velvet-sofa",
    src: "img/velvet-sofa.jpg",
    cat: "biz",
    title: "Velvet · Мебельный салон",
    tools: ["Photoshop", "Figma"],
    desc: "Продуктовый креатив со скидкой. Тёплый минимализм, аккуратная типографика цены и бейджи преимуществ.",
    features: ["Тёплый минимализм", "Старая / новая цена", "Бейджи доставки и сборки"],
  },
  {
    kind: "work",
    slug: "umka-italy",
    src: "img/umka-italy.jpg",
    cat: "biz",
    title: "UMKA Tour · Италия",
    tools: ["Photoshop"],
    desc: "Тревел-креатив прямых рейсов. Тёплый закатный кадр Колизея, плашки-таблетки и цена оффера.",
    features: ["Закатная палитра", "Плашки-таблетки", "Цена-оффер"],
  },
  {
    kind: "work",
    slug: "archspace",
    src: "img/archspace.jpg",
    cat: "biz",
    title: "ArchSpace · Архитектура",
    tools: ["Photoshop", "Figma"],
    desc: "B2B-креатив архитектурного бюро. 3D-визуализация объекта, строгая сетка и перечисление услуг.",
    features: ["3D-визуализация", "Строгая сетка", "B2B-тон"],
  },
  {
    kind: "work",
    slug: "green-cleaning-1",
    src: "img/green-cleaning-1.jpg",
    cat: "biz",
    title: "Green Cleaning · Уборка после ремонта",
    tools: ["Photoshop"],
    desc: "Перформанс-креатив клининга. Дружелюбная розовая палитра, цена за м² и быстрый CTA.",
    features: ["Дружелюбный тон", "Цена за м²", "Сильный CTA"],
  },
  {
    kind: "work",
    slug: "green-cleaning-2",
    src: "img/green-cleaning-2.jpg",
    cat: "biz",
    title: "Green Cleaning · Генеральная уборка",
    tools: ["Photoshop"],
    desc: "Серия клининг-креативов. Единая фирменная система, акцентные плашки и оффер по срокам.",
    features: ["Серийная система", "Акцентные плашки", "Оффер по срокам"],
  },
  {
    kind: "work",
    slug: "dentium-implants",
    src: "img/dentium-implants.jpg",
    cat: "biz",
    title: "Clinic SARA · Импланты Dentium",
    tools: ["Photoshop"],
    desc: "Медицинский продуктовый креатив. Чистый фон, макро продукта и оффер рассрочки Kaspi.",
    features: ["Макро продукта", "Чистый медицинский тон", "Оффер рассрочки"],
  },
  {
    kind: "work",
    slug: "solar-huawei",
    src: "img/solar-huawei.jpg",
    cat: "social",
    title: "Solar · Huawei",
    tools: ["Photoshop", "Figma"],
    desc: "Сторис-креатив про солнечные станции. Вертикальный формат, природный кадр и интерактивный CTA-калькулятор.",
    features: ["Формат 9:16", "Природный кадр", "CTA-калькулятор"],
  },
  {
    kind: "work",
    slug: "kids-dentist",
    src: "img/kids-dentist.jpg",
    cat: "social",
    title: "Детский стоматолог · Marat Nurai",
    tools: ["Photoshop"],
    desc: "Сторис для детской стоматологии. Мягкая бирюзовая палитра, дружелюбные бейджи и круглый стикер «записаться».",
    features: ["Формат 9:16", "Мягкая палитра", "Круглый стикер-CTA"],
  },
  {
    kind: "work",
    slug: "fitness-minus2",
    src: "img/fitness-minus2.jpg",
    cat: "social",
    title: "Фитнес · Минус 2 кг в неделю",
    tools: ["Photoshop"],
    desc: "Сторис фитнес-программы. Динамичный портрет, цифры оффера и заметный CTA «оставляй заявку».",
    features: ["Формат 9:16", "Динамичный портрет", "Цифры-оффер"],
  },
  {
    kind: "work",
    slug: "british-education-webinar",
    src: "img/british-education-webinar.jpg",
    cat: "event",
    title: "British Education in Kazakhstan",
    tools: ["Photoshop", "Figma"],
    desc: "Анонс онлайн-вебинара DZU с Head of Student Recruitment. Строгая бизнес-подача, диагональная сетка и крупный двуязычный заголовок.",
    features: ["Диагональная сетка", "Деловой портрет", "Двуязычный заголовок"],
  },
  {
    kind: "work",
    slug: "dmuk-inside-webinar",
    src: "img/dmuk-inside-webinar.jpg",
    cat: "event",
    title: "Учёба в DMUK изнутри",
    tools: ["Photoshop", "Figma"],
    desc: "Анонс эфира «честный разговор со студентом». Стильный чёрно-белый портрет, акцентный красный и чистая иерархия.",
    features: ["Ч/б обработка портрета", "Акцентный красный", "Чистая иерархия"],
  },
  {
    kind: "work",
    slug: "english-online",
    src: "img/english-online.jpg",
    cat: "edu",
    title: "Английский онлайн",
    tools: ["Photoshop", "Figma"],
    desc: "Лид-креатив на онлайн-уроки английского. Лёгкий городской фон с Биг-Беном, иконки-преимущества и плашка цены.",
    features: ["Иконочные буллеты", "Тематический фон", "Плашка-оффер"],
  },
  {
    kind: "work",
    slug: "novyi-dom-transformer",
    src: "img/novyi-dom-transformer.jpg",
    cat: "biz",
    title: "Новый дом · Кровать-трансформер",
    tools: ["Photoshop"],
    desc: "Продуктовый креатив студии мебели. Крупный зелёный заголовок, акцент на подарке Lego и явный дедлайн акции.",
    features: ["Крупный заголовок", "Подарок-оффер", "Дедлайн акции"],
  },
  {
    kind: "work",
    slug: "eshburger",
    src: "img/eshburger.jpg",
    cat: "biz",
    title: "ЕшБургер · Доставка Glovo",
    tools: ["Photoshop"],
    desc: "Аппетитный фуд-креатив. Тёплый огненный фон, динамичные брызги и интеграция с приложением доставки.",
    features: ["Аппетитная съёмка", "Огненный фон", "Интеграция с Glovo"],
  },
  {
    kind: "work",
    slug: "pugasov-vacancy",
    src: "img/pugasov-vacancy.jpg",
    cat: "biz",
    title: "Усадьба Пугасова · Вакансия",
    tools: ["Photoshop"],
    desc: "HR-креатив ресторана. Премиальная сине-золотая палитра, рукописный акцент и крупный номер для связи.",
    features: ["Сине-золотая палитра", "Рукописный акцент", "Крупный контакт"],
  },
  {
    kind: "work",
    slug: "beautyshop-deo",
    src: "img/beautyshop-deo.jpg",
    cat: "biz",
    title: "Beauty Shop · Дезодорант No Sweat",
    tools: ["Photoshop"],
    desc: "Продуктовый креатив для бьюти-магазина. Чистый светлый фон, акцент на оригинальности и цене.",
    features: ["Чистый продуктовый фон", "Бейдж «оригинал»", "Акцент на цене"],
  },
  {
    kind: "work",
    slug: "imperia-office",
    src: "img/imperia-office.jpg",
    cat: "biz",
    title: "Империя мебели · Офисные кресла",
    tools: ["Photoshop"],
    desc: "B2B-креатив для офисной мебели. Контрастная красно-чёрная геометрия, чек-лист гарантий и подарок-оффер.",
    features: ["Геометричный фон", "Чек-лист гарантий", "Подарок-оффер"],
  },
  {
    kind: "work",
    slug: "sara-crowns",
    src: "img/sara-crowns.jpg",
    cat: "biz",
    title: "Clinic SARA · Циркониевые коронки",
    tools: ["Photoshop"],
    desc: "Медицинский креатив со скидкой. Светлая бежевая подача, цена в рассрочку Kaspi и оффер для первых клиентов.",
    features: ["Чистый медицинский тон", "Оффер рассрочки", "Скидка-хук"],
  },
  {
    kind: "work",
    slug: "sara-braces",
    src: "img/sara-braces.jpg",
    cat: "biz",
    title: "Clinic SARA · Брекеты",
    tools: ["Photoshop"],
    desc: "Стоматологический креатив. Тёплый коричневый фон, оффер рассрочки и подарочные бонусы для первых клиентов.",
    features: ["Тёплый фон", "Рассрочка Kaspi", "Бонусы-подарки"],
  },
  {
    kind: "work",
    slug: "torgservis",
    src: "img/torgservis.jpg",
    cat: "biz",
    title: "Торг Сервис Астана · Оборудование",
    tools: ["Photoshop"],
    desc: "B2B-креатив торгового оборудования. Светлая техничная подача, рассрочка 0% и логотипы банков-партнёров.",
    features: ["Техничная подача", "Рассрочка 0%", "Логотипы партнёров"],
  },
  {
    kind: "work",
    slug: "mamino-acting",
    src: "img/mamino-acting.jpg",
    cat: "biz",
    title: "Мамино счастье · Актёрское мастерство",
    tools: ["Photoshop"],
    desc: "Креатив детского кружка. Нежная пастельная палитра, иконки-детали и заметная цена.",
    features: ["Пастельная палитра", "Иконки-детали", "Акцент на цене"],
  },
  {
    kind: "work",
    slug: "funtown",
    src: "img/funtown.jpg",
    cat: "biz",
    title: "FunTown · Детские праздники",
    tools: ["Photoshop"],
    desc: "Креатив семейного клуба. Розовая праздничная подача, эмоциональный кадр и оффер по бронированию банкета.",
    features: ["Праздничная палитра", "Эмоциональный кадр", "Оффер-бронь"],
  },
  {
    kind: "work",
    slug: "florion",
    src: "img/florion.jpg",
    cat: "biz",
    title: "Florion · Доставка цветов",
    tools: ["Photoshop"],
    desc: "Имиджевый креатив цветочного бренда. Глубокий синий фон, хлёсткий слоган и цена с рукописной стрелкой.",
    features: ["Глубокий синий фон", "Хлёсткий слоган", "Цена-оффер"],
  },
  {
    kind: "work",
    slug: "zarin-home",
    src: "img/zarin-home.jpg",
    cat: "biz",
    title: "Zarin Home · Текстиль",
    tools: ["Photoshop"],
    desc: "Продуктовый креатив домашнего текстиля. Контраст чёрного и жёлтого, акцент на подарке за покупку.",
    features: ["Контраст чёрный / жёлтый", "Подарок за покупку", "Дедлайн акции"],
  },
  {
    kind: "work",
    slug: "blackfriday-dental",
    src: "img/blackfriday-dental.jpg",
    cat: "biz",
    title: "Black Friday · Стоматология",
    tools: ["Photoshop"],
    desc: "Распродажный креатив. Гранж-фактуры, синий акцент, эмоциональный портрет и крупный процент скидки.",
    features: ["Гранж-фактуры", "Эмоция в кадре", "Крупная скидка"],
  },
  {
    kind: "work",
    slug: "ilock",
    src: "img/ilock.jpg",
    cat: "biz",
    title: "iLock · Электронные замки",
    tools: ["Photoshop"],
    desc: "Премиальный продуктовый креатив. Тёмный гранёный фон, красные акценты, старая/новая цена и способы оплаты.",
    features: ["Гранёный тёмный фон", "Старая / новая цена", "Способы оплаты"],
  },
  {
    kind: "work",
    slug: "novyi-dom-kids",
    src: "img/novyi-dom-kids.jpg",
    cat: "biz",
    title: "Новый дом · Мебель для детской",
    tools: ["Photoshop"],
    desc: "Продуктовый креатив детской мебели. Свежая подача, диагональный кадр интерьера и подарок Lego.",
    features: ["Диагональная композиция", "Подарок-оффер", "Свежая палитра"],
  },
  {
    kind: "work",
    slug: "furore-sterilizer",
    src: "img/furore-sterilizer.jpg",
    cat: "biz",
    title: "Furore · Сухожаровой шкаф",
    tools: ["Photoshop"],
    desc: "Продуктовый креатив для бьюти-оборудования. Тёмный фон с тропическими листьями, скидка и старая/новая цена.",
    features: ["Тёмный фон + листья", "Скидка-хук", "Старая / новая цена"],
  },
  {
    kind: "work",
    slug: "lasvegas-happyhour",
    src: "img/lasvegas-happyhour.jpg",
    cat: "biz",
    title: "Las Vegas · Happy Hour",
    tools: ["Photoshop"],
    desc: "Фуд-креатив караоке-бара. Тёмная атмосферная сцена, аппетитная съёмка блюда и оффер по времени.",
    features: ["Атмосферная сцена", "Аппетитная съёмка", "Оффер по времени"],
  },
  {
    kind: "work",
    slug: "megadent-vacancy",
    src: "img/megadent-vacancy.jpg",
    cat: "biz",
    title: "МегаДент · Вакансии для врачей",
    tools: ["Photoshop"],
    desc: "HR-креатив стоматологии. Воздушный светлый фон, дружелюбный портрет и понятный CTA по ссылке.",
    features: ["Воздушный фон", "Дружелюбный портрет", "Понятный CTA"],
  },
  {
    kind: "work",
    slug: "safart-kitchen",
    src: "img/safart-kitchen.jpg",
    cat: "biz",
    title: "Safart · Кухни на заказ",
    tools: ["Photoshop"],
    desc: "Продуктовый креатив мебельной студии. Крупный зелёный заголовок, акцент на подарке и дедлайн акции.",
    features: ["Крупный заголовок", "Подарок-оффер", "Дедлайн акции"],
  },
  {
    kind: "work",
    slug: "modern-house-story",
    src: "img/modern-house-story.jpg",
    cat: "social",
    title: "Современный дом под ключ",
    tools: ["Photoshop", "Figma"],
    desc: "Сторис-креатив для строительной компании. Вертикальный формат, 3D-визуализация дома, иконки-преимущества и CTA на каталог.",
    features: ["Формат 9:16", "3D-визуализация", "CTA на каталог"],
  },
];
